apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlabrunner-docker-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/gitlab-runner/docker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlabrunner-config-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/gitlab-runner/config
