apiVersion: v1
kind: Service
metadata:
  name: gitlabrunner-service
spec:
  selector:
    app: GITLABRUNNER
  type: NodePort
  ports:
    - name: gitlabrunner-session-server-port
      protocol: TCP
      port: 8093
      targetPort: 8093
      nodePort: 32093
