apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: gitlab-config-pv
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: gitlab-logs-pv
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: gitlab-data-pv
  resources:
    requests:
      storage: 40Gi
