apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: JENKINS
  type: NodePort
  ports:
    - name: jenkins-server-http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30880
    - name: jenkins-server-agent-port
      protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30500
