apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: NEXUS
  type: NodePort
  ports:
    - name: nexus-http-port
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081
