apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: redmine-data-pv
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-db-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: redmine-db-data-pv
  resources:
    requests:
      storage: 40Gi
