apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/redmine/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-db-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/redmine/db-data
