apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  selector:
    app: REDMINE
  type: NodePort
  ports:
    - name: redmine-http-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32300
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-db-service
spec:
  selector:
    app: REDMINEDB
  type: NodePort
  ports:
    - name: redmine-db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31432
