apiVersion: v1
kind: Service
metadata:
  name: registry-server-service
spec:
  selector:
    app: REGISTRYSERVER
  type: NodePort
  ports:
    - name: registry-server-port
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 31500
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui-service
spec:
  selector:
    app: REGISTRYUI
  type: NodePort
  ports:
    - name: registry-ui-http-port
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31182
