apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  selector:
    app: SONARQUBE
  type: NodePort
  ports:
    - name: sonarqube-http-port
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30900
