apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  selector:
    app: SONARQUBE
  type: NodePort
  ports:
    - name: sonarqube-http-port
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30900
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db-service
spec:
  selector:
    app: SONARQUBEDB
  type: NodePort
  ports:
    - name: sonarqube-pgsql-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
