apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: sonarqube-data-pv
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: sonarqube-logs-pv
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: sonarqube-extensions-pv
  resources:
    requests:
      storage: 4Gi
