apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SONARQUBE
  template:
    metadata:
      name: sonarqube-lab
      labels:
        app: SONARQUBE
    spec:
#      securityContext:
#        runAsUser: {{ .Values.security.uid }}
#        runAsGroup: {{ .Values.security.gid }}
      hostname: sonarqube
      containers:
        - name: sonarqube
          image: sonarqube:9.8.0-community
          ports:
            - containerPort: 9100
          env:
            - name: SONAR_WEB_PORT
              value: "9100"
            - name: SONAR_WEB_HOST
              value: "0.0.0.0"
            - name: SONAR_WEB_CONTEXT
              value: "/sonarqube"
            - name: SONAR_JDBC_USERNAME
              value: "sonar"
            - name: SONAR_JDBC_PASSWORD
              value: "sonar123"
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://sonarqube-db-service:5432/sonarqube?currentSchema=public"
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data-vol
            - mountPath: /opt/sonarqube/logs
              name: sonarqube-logs-vol
            - mountPath: /opt/sonarqube/extensions
              name: sonarqube-extensions-vol
      volumes:
        - name: sonarqube-data-vol
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        - name: sonarqube-logs-vol
          persistentVolumeClaim:
            claimName: sonarqube-logs-pvc
        - name: sonarqube-extensions-vol
          persistentVolumeClaim:
            claimName: sonarqube-extensions-pvc
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SONARQUBEDB
  template:
    metadata:
      name: sonarqube-db-lab
      labels:
        app: SONARQUBEDB
    spec:
      hostname: sonarqube-db
      containers:
        - name: sonarqube-db
          image: postgres:15.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "sonar"
            - name: POSTGRES_PASSWORD
              value: "sonar123"
            - name: POSTGRES_DB
              value: "sonarqube"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sonarqube-db-data-vol
      volumes:
        - name: sonarqube-db-data-vol
          persistentVolumeClaim:
            claimName: sonarqube-db-data-pvc
      restartPolicy: Always
