apiVersion: v1
kind: Service
metadata:
  name: trivy-server-service
spec:
  selector:
    app: TRIVYSERVER
  type: NodePort
  ports:
    - name: trivy-server-http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31180
