apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-cache-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/trivy/cache
