apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: trivy-cache-pv
  resources:
    requests:
      storage: 40Gi
