#
## GitLab

GITLAB_RUNNER_BASEDIR="volumes/gitlab"
GITLAB_RUNNER_CONFIG=$GITLAB_RUNNER_BASEDIR/config
GITLAB_RUNNER_DATA=$GITLAB_RUNNER_BASEDIR/data
GITLAB_RUNNER_LOGS=$GITLAB_RUNNER_BASEDIR/logs

#
## GitLab Runner

GITLAB_RUNNER_BASEDIR="volumes/gitlab-runner"
GITLAB_RUNNER_CONFIG=$GITLAB_RUNNER_BASEDIR/config
GITLAB_RUNNER_DOCKER=$GITLAB_RUNNER_BASEDIR/docker
