#
## GitLab

GITLAB_BASEDIR="volumes/gitlab"
GITLAB_CONFIG=$GITLAB_BASEDIR/config
GITLAB_DATA=$GITLAB_BASEDIR/data
GITLAB_LOGS=$GITLAB_BASEDIR/logs

#
## GitLab Runner

GITLAB_RUNNER_BASEDIR="volumes/gitlab-runner"
GITLAB_RUNNER_CONFIG=$GITLAB_RUNNER_BASEDIR/config
GITLAB_RUNNER_DOCKER=$GITLAB_RUNNER_BASEDIR/docker

#
# Jenkins
JENKINS_BASEDIR="volumes/jenkins"
JENKINS_DATA_DIR="$JENKINS_BASEDIR/data"
